export const STATUS_CODE_SUCCESS = 200 // "OK"
export const STATUS_CODE_MALFORMED_REQUEST = 400 // "Bad Request"
export const STATUS_CODE_THROW_ABORT = 403 // "Forbidden"
export const STATUS_CODE_SHIELD_VALIDATION_ERROR = 422 // "Unprocessable Content"
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500  // "Internal Server Error"
