export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_MALFORMED_REQUEST = 400
export const STATUS_CODE_ABORT = 403
export const STATUS_CODE_SHIELD_VALIDATION_ERROR = 422
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500
