export const STATUS_CODE_SUCCESS = 200 // "OK"
export const STATUS_CODE_MALFORMED_REQUEST = 400 // "Bad Request"
export const STATUS_BODY_MALFORMED_REQUEST = 'Malformed Telefunc Request'
export const STATUS_CODE_THROW_ABORT = 403 // "Forbidden"
export const STATUS_CODE_SHIELD_VALIDATION_ERROR = 422 // "Unprocessable Content"
export const STATUS_BODY_SHIELD_VALIDATION_ERROR = 'Shield Validation Error'
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500 // "Internal Server Error"
export const STATUS_BODY_INTERNAL_SERVER_ERROR = 'Internal Server Error'
export const MULTIPART_PLACEHOLDER_KEY = '__telefunc_multipart'
