import { type DocsGraph } from '@unterberg/nivel'

export const docsGraph = {
  items: [
    {
      kind: 'section',
      id: 'documentation',
      title: 'Docs',
      navTitle: 'Docs',
      items: [
        {
          kind: 'group',
          id: 'getting-started',
          title: 'Getting Started',
          items: [
            {
              kind: 'page',
              id: 'quickStart',
              title: 'Quick Start',
              slug: 'quick-start',
              source: 'content/quick-start/content.mdx',
              aliases: ['start', 'intro'],
              description: 'Get started with telefunc and learn how to create your own documentation site.',
            },
            {
              kind: 'page',
              id: 'concepts',
              title: 'Concepts',
              slug: 'concepts',
              source: 'content/concepts/content.mdx',
              description: 'Learn the core concepts behind telefunc and how it works under the hood.',
            },
            {
              kind: 'page',
              id: 'bestPractices',
              title: 'Best Practices',
              slug: 'best-practices',
              source: 'content/best-practices/content.mdx',
              description: 'Discover best practices for structuring your documentation and writing effective content.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'guides',
          title: 'Guides',
          items: [
            {
              kind: 'group',
              id: 'server-guides',
              title: 'Server Integration',
              href: '/docs/server-integration/',
              collapsible: {
                isDefaultOpen: false,
              },
              items: [
                {
                  kind: 'page',
                  id: 'serverIntegration',
                  title: 'Server Integration',
                  slug: 'server-integration',
                  source: 'content/server-integration/content.mdx',
                  aliases: ['server'],
                  description: 'Learn how to integrate telefunc with your server and deploy your documentation site.',
                },
                {
                  kind: 'page',
                  id: 'next',
                  title: 'Next.js',
                  slug: 'next',
                  source: 'content/next/content.mdx',
                  description: 'Learn how to integrate Telefunc with Next.js.',
                },
                {
                  kind: 'page',
                  id: 'svelteKit',
                  title: 'SvelteKit',
                  slug: 'svelte-kit',
                  source: 'content/svelte-kit/content.mdx',
                  description: 'Learn how to integrate Telefunc with SvelteKit.',
                },
                {
                  kind: 'page',
                  id: 'vike',
                  title: 'Vike',
                  slug: 'vike',
                  source: 'content/vike/content.mdx',
                  description: 'Learn how to integrate Telefunc with Vike.',
                },
                {
                  kind: 'page',
                  id: 'nuxt',
                  title: 'Nuxt',
                  slug: 'nuxt',
                  source: 'content/nuxt/content.mdx',
                  description: 'Learn how to integrate Telefunc with Nuxt.',
                },
                {
                  kind: 'page',
                  id: 'reactRouter',
                  title: 'React Router',
                  slug: 'react-router',
                  source: 'content/react-router/content.mdx',
                  description: 'Learn how to integrate Telefunc with React Router.',
                },
                {
                  kind: 'page',
                  id: 'reactNative',
                  title: 'React Native',
                  slug: 'react-native',
                  source: 'content/react-native/content.mdx',
                  description: 'Learn how to use Telefunc with React Native.',
                },
                {
                  kind: 'page',
                  id: 'bundler',
                  title: 'Bundlers',
                  slug: 'bundler',
                  source: 'content/bundler/content.mdx',
                  description:
                    'Learn how to use Telefunc with bundlers and environments that do not rely on a transformer plugin.',
                },
              ],
            },
            {
              kind: 'page',
              id: 'initialData',
              title: 'Initial Data',
              slug: 'initial-data',
              source: 'content/initial-data/content.mdx',
              description:
                'Learn how to provide initial data for your documentation pages and enhance the user experience.',
            },
            {
              kind: 'page',
              id: 'permissions',
              title: 'Permissions',
              slug: 'permissions',
              source: 'content/permissions/content.mdx',
              description: 'Learn how to manage permissions for your documentation site and control access to content.',
            },
            {
              kind: 'page',
              id: 'validation',
              title: 'Validation',
              slug: 'validation',
              source: 'content/validation/content.mdx',
              aliases: ['form-validation'],
              description: 'Learn how to validate your documentation content and ensure it meets quality standards.',
            },
            {
              kind: 'page',
              id: 'fileUploads',
              title: 'File Uploads',
              slug: 'file-uploads',
              source: 'content/file-uploads/content.mdx',
              aliases: ['file-upload'],
              description:
                'Learn how to handle file uploads in your documentation site and provide a seamless experience for users.',
            },
            {
              kind: 'page',
              id: 'errorHandling',
              title: 'Error Handling',
              slug: 'error-handling',
              source: 'content/error-handling/content.mdx',
              description:
                'Learn how to handle errors in your documentation site and provide helpful feedback to users.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'learn-more',
          title: 'Learn More',
          items: [
            {
              kind: 'page',
              id: 'whySchemaless',
              title: 'Why Schemaless?',
              slug: 'why-schemaless',
              source: 'content/why-schemaless/content.mdx',
              description: 'Learn about the benefits of using a schemaless approach for your documentation content.',
            },
            {
              kind: 'page',
              id: 'howItWorks',
              title: 'How It Works',
              slug: 'how-it-works',
              source: 'content/how-it-works/content.mdx',
              description:
                'Learn how telefunc works under the hood and how it provides a seamless documentation experience.',
            },
          ],
        },
      ],
    },
    {
      kind: 'section',
      id: 'api',
      title: 'API',
      items: [
        {
          kind: 'page',
          id: 'apiOverview',
          title: 'API Overview',
          slug: 'api',
          source: 'content/api/content.mdx',
          tableOfContents: false,
          showInNav: false,
          description: 'Get started with telefunc and learn how to create your own documentation site.',
        },
        {
          kind: 'group',
          id: 'server-api',
          title: 'Server',
          items: [
            {
              kind: 'page',
              id: 'apiTelefunc',
              title: '`telefunc()`',
              slug: 'telefunc',
              source: 'content/telefunc/content.mdx',
              description: 'Learn about the telefunc API and how to use it to create powerful documentation sites.',
            },
            {
              kind: 'page',
              id: 'throwAbort',
              title: '`throw Abort()`',
              slug: 'throw-abort',
              source: 'content/throw-abort/content.mdx',
              aliases: ['Abort'],
              description:
                'Learn about the throwAbort API and how to use it to handle errors in your documentation site.',
            },
            {
              kind: 'page',
              id: 'getContext',
              title: '`getContext()`',
              slug: 'get-context',
              source: 'content/get-context/content.mdx',
              aliases: ['getContext'],
              description:
                'Learn about the getContext API and how to use it to access context in your documentation site.',
            },
            {
              kind: 'page',
              id: 'shield',
              title: '`shield()`',
              slug: 'shield',
              source: 'content/shield/content.mdx',
              description:
                'Learn about the shield API and how to use it to protect your documentation site from unauthorized access.',
            },
            {
              kind: 'page',
              id: 'onBug',
              title: '`onBug()`',
              slug: 'on-bug',
              source: 'content/on-bug/content.mdx',
              aliases: ['onBug'],
              description: 'Learn about the onBug API and how to use it to handle bugs in your documentation site.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'client-api',
          title: 'Client',
          items: [
            {
              kind: 'page',
              id: 'onAbort',
              title: '`onAbort()`',
              slug: 'on-abort',
              source: 'content/on-abort/content.mdx',
              aliases: ['onAbort'],
              description:
                'Learn about the onAbort API and how to use it to handle aborted requests in your documentation site.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'config-api',
          title: 'Config',
          items: [
            {
              kind: 'page',
              id: 'telefuncUrl',
              title: '`telefuncURL`',
              slug: 'telefunc-url',
              source: 'content/telefunc-url/content.mdx',
              aliases: ['telefuncUrl'],
              description:
                'Learn about the telefunc URL structure and how to use it to organize your documentation content.',
            },
            {
              kind: 'page',
              id: 'disableNamingConvention',
              title: '`disableNamingConvention`',
              slug: 'disable-naming-convention',
              source: 'content/disable-naming-convention/content.mdx',
              aliases: ['disableNamingConvention'],
              description:
                'Learn how to disable the naming convention for your documentation content and use custom names.',
            },
            {
              kind: 'page',
              id: 'httpHeaders',
              title: '`httpHeaders`',
              slug: 'http-headers',
              source: 'content/http-headers/content.mdx',
              aliases: ['httpHeaders'],
              description:
                'Learn about the HTTP headers used in telefunc and how to customize them for your documentation site.',
            },
            {
              kind: 'page',
              id: 'fetch',
              title: '`fetch`',
              slug: 'fetch',
              source: 'content/fetch/content.mdx',
              description:
                'Learn how to use the fetch API in your documentation site and make requests to your server.',
            },
            {
              kind: 'page',
              id: 'telefuncFiles',
              title: '`telefuncFiles`',
              slug: 'telefunc-files',
              source: 'content/telefunc-files/content.mdx',
              aliases: ['telefuncFiles'],
              description: 'Learn about telefunc files and how to use them to organize your documentation content.',
            },
            {
              kind: 'page',
              id: 'root',
              title: '`root`',
              slug: 'root',
              source: 'content/root/content.mdx',
              description:
                'Welcome to the telefunc documentation! This is your starting point for learning about telefunc and how to use it to create powerful documentation sites.',
            },
            {
              kind: 'page',
              id: 'configShield',
              title: '`config.shield`',
              slug: 'shield-config',
              source: 'content/shield-config/content.mdx',
              description: 'Learn how to configure shield generation in development and production.',
            },
            {
              kind: 'page',
              id: 'log',
              title: '`log`',
              slug: 'log',
              source: 'content/log/content.mdx',
              description: 'Learn about the log API and how to use it to log information in your documentation site.',
            },
          ],
        },
      ],
    },
  ],
} satisfies DocsGraph
