import { testGenerateShield } from './generateShield.js'
import { expect, describe, it } from 'vitest'

describe('generateShield', () => {
  it('generateShield, one telefunction', async () => {
    const src = `export function doSomething(arg: string) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";

      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true })
      "
    `)
  })

  it('generateShield, two telefunctions', async () => {
    const src = `export function doSomething(arg: string) {

}

export function doSomethingElse(arg: string | number, arg2: { val?: number }) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";

      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true })
      __telefunc_shield(doSomethingElse, [__telefunc_t.or(__telefunc_t.number, __telefunc_t.string), { val: __telefunc_t.optional(__telefunc_t.number) }], { __autoGenerated: true })
      "
    `)
  })

  it('generateShield, real use case', async () => {
    const src = `import { __decorateTelefunction } from "telefunc";export function onFoo(bar: string, baz: Attending) {
        console.log({ bar });
}

export enum Attending {
        MAYBE = 'MAYBE',
        ATTENDING = 'ATTENDING',
        NOT_ATTENDING = 'NOT_ATTENDING',
        UNKNOWN = 'UNKNOWN'
}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";

      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onFoo, [__telefunc_t.string, __telefunc_t.or(__telefunc_t.const('UNKNOWN'), __telefunc_t.const('NOT_ATTENDING'), __telefunc_t.const('ATTENDING'), __telefunc_t.const('MAYBE'))], { __autoGenerated: true })
      "
    `)
  })

  it('edge cases', async () => {
    const code = `export { someFunc as onLoad }

const someFunc = async ({ name }: { name: string }) => {
  const message = 'Welcome ' + name
  return { message }
}`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";

      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(someFunc, [{ name: __telefunc_t.string }], { __autoGenerated: true })
      "
    `)
  })
})
