import { testGenerateShield } from './generateShield.js'
import { expect, describe, it } from 'vitest'

describe('generateShield', () => {
  it('generateShield, one telefunction', async () => {
    const src = `export function doSomething(arg: string) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, two telefunctions', async () => {
    const src = `export function doSomething(arg: string) {

}

export function doSomethingElse(arg: string | number, arg2: { val?: number }) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      __telefunc_shield(doSomethingElse, [__telefunc_t.or(__telefunc_t.number, __telefunc_t.string), { val: __telefunc_t.optional(__telefunc_t.number) }], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, real use case', async () => {
    const src = `import { __decorateTelefunction } from "telefunc";export function onFoo(bar: string, baz: Attending) {
        console.log({ bar });
}

export enum Attending {
        MAYBE = 'MAYBE',
        ATTENDING = 'ATTENDING',
        NOT_ATTENDING = 'NOT_ATTENDING',
        UNKNOWN = 'UNKNOWN'
}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onFoo, [__telefunc_t.string, __telefunc_t.or(__telefunc_t.const('UNKNOWN'), __telefunc_t.const('NOT_ATTENDING'), __telefunc_t.const('ATTENDING'), __telefunc_t.const('MAYBE'))], { __autoGenerated: true });
      "
    `)
  })

  it('edge cases', async () => {
    const code = `export { someFunc as onLoad }

const someFunc = async ({ name }: { name: string }) => {
  const message = 'Welcome ' + name
  return { message }
}`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(someFunc, [{ name: __telefunc_t.string }], { __autoGenerated: true });
      "
    `)
  })

  it('callable arg whose return is void/Promise<void> asserts `undefined` at runtime', async () => {
    // A callback typed `() => Promise<void>` must actually return `undefined` at runtime —
    // otherwise `if (await cb()) …` branches unpredictably on client-returned garbage. The
    // sub-shield therefore emits `[const(undefined)]` for void returns, not nothing.
    const code = `
export function onWithVoidCallback(cb: (percent: number) => Promise<void>) {}
export function onWithTypedCallback(cb: (n: number) => Promise<number>) {}
`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onWithVoidCallback, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onWithVoidCallback, { "0": { return: [__telefunc_t.const(undefined)] } });
      __telefunc_shield(onWithTypedCallback, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onWithTypedCallback, { "0": { return: [__telefunc_t.number] } });
      "
    `)
  })

  it('shielded-marker entries: every type (void, never, unknown) yields a concrete runtime shield', async () => {
    const code = `
import type { TELEFUNC_SHIELDS } from './shield-key.js'
declare global {
  namespace Telefunc {
    interface ShieldTypeMap {}
  }
}
type Payload<T, U> = {
  readonly [TELEFUNC_SHIELDS]: {
    data: T
    ack: U
    empty: never
  }
}
export function onMixed(arg: Payload<string, void>) {}
`
    // data = string → __telefunc_t.string
    // ack  = void   → __telefunc_t.const(undefined)  (accepts only undefined)
    // empty = never → __telefunc_t.never             (rejects every value)
    // No entry is silently skipped — every TS type position gets a concrete runtime validator.
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onMixed, [{  }], { __autoGenerated: true });
      __applyArgumentShields(onMixed, { "0": { data: [__telefunc_t.string], ack: [__telefunc_t.const(undefined)], empty: [__telefunc_t.never] } });
      "
    `)
  })

  it('ExtensionType picks most-specific when multiple ShieldTypeMap entries match', async () => {
    const code = `
declare global {
  namespace Telefunc {
    interface ShieldTypeMap {
      animal: { __brand_animal: true }
      dog: { __brand_animal: true; __brand_dog: true }
    }
  }
}
export function onAnimalArg(a: { __brand_animal: true }) {}
export function onDogArg(d: { __brand_animal: true; __brand_dog: true }) {}
`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onAnimalArg, [__telefunc_t.animal], { __autoGenerated: true });
      __telefunc_shield(onDogArg, [__telefunc_t.dog], { __autoGenerated: true });
      "
    `)
  })
})
