export { shield }
export { shieldIsMissing }
export { shieldApply }
export { shieldToHumandReadable }

// TODO/now-ish make variable naming in this file more consistent https://github.com/telefunc/telefunc/pull/247

import { assert, assertUsage } from '../../utils/assert.js'
import { isCallable } from '../../utils/isCallable.js'
import { isPlainObject } from '../../utils/isPlainObject.js'
import { unique } from '../../utils/unique.js'
import { isLazyFile, isLazyBlob } from './multipart/LazyFile.js'

const shieldKey = '__telefunc_shield'
const isVerifierKey = '__telefunc_isVerifier'
const isVerifierTupleKey = '__telefunc_isVerifierTuple'

type ShieldOptions = { __autoGenerated?: boolean }

function shield<TelefunctionArgs extends unknown[], Telefunction extends (...args: TelefunctionArgs) => unknown>(
  telefunction: Telefunction,
  verifiers: { [K in keyof TelefunctionArgs]: ShieldDefinition<TelefunctionArgs[K]> },
  options?: ShieldOptions,
): Telefunction {
  assertUsage(isTelefunction(telefunction), '[shield(telefunction, verifiers)] `telefunction` should be a function')
  assertShield(verifiers)
  installShield(telefunction, verifiers, !!options?.__autoGenerated)
  return telefunction
}

type Telefunction = Function & {
  [K in typeof shieldKey]?: unknown
}

type SchemaIssue = {
  message?: unknown
  path?: readonly (string | number)[]
}
type StandardSchemaResult = {
  issues?: readonly SchemaIssue[]
  value?: unknown
}
type StandardSchema<Input = unknown> = {
  readonly '~standard': {
    readonly version: number
    readonly vendor: string
    validate(value: unknown): StandardSchemaResult | Promise<StandardSchemaResult>
    readonly types?: {
      readonly input: Input
      readonly output: unknown
    }
  }
}
type ZodLikeSchema<Output = unknown> = {
  safeParse(value: unknown):
    | {
        success: true
        data: Output
      }
    | {
        success: false
        error: {
          issues?: readonly SchemaIssue[]
        }
      }
}
type ZodLikeSchemaResult<Output = unknown> = ReturnType<ZodLikeSchema<Output>['safeParse']>
type SchemaLike<T = unknown> = StandardSchema<T> | ZodLikeSchema<T>
type ShieldDefinition<T> = T | SchemaLike<T>

function assertShield(telefunctionShield: unknown): asserts telefunctionShield is TelefunctionShield {
  assertUsage(
    Array.isArray(telefunctionShield) || isVerifierTuple(telefunctionShield),
    [
      '[shield(telefunction, verifiers)]',
      '`verifiers` should be an array.',
      `Example of correct usage: \`shield(telefunction, [shield.type.string])\`.`,
      `Example of wrong usage: \`shield(telefunction, shield.type.string)\`.`,
    ].join(' '),
  )
}

function isTelefunction(thing: unknown): thing is Telefunction {
  return isCallable(thing) && !isVerifier(thing)
}

function installShield(telefunction: Telefunction, verifiers: unknown[], isGeneration: boolean): void {
  // A shield is already defined, skip auto-generation.
  if (telefunction[shieldKey] && isGeneration) return
  telefunction[shieldKey] = verifiers
}

function shieldIsMissing(telefunction: Telefunction): boolean {
  const telefunctionShield = getTelefunctionShield(telefunction)
  return telefunctionShield === null
}

function shieldApply(telefunction: Telefunction, args: unknown[]): true | string {
  const telefunctionShield = getTelefunctionShield(telefunction)
  assert(telefunctionShield !== null)
  return verifyOuter(telefunctionShield, args)
}

type TelefunctionShield = unknown[] | Verifier
function getTelefunctionShield(telefunction: Telefunction): TelefunctionShield | null {
  return (telefunction as any)[shieldKey] || null
}

function shieldToHumandReadable(telefunctionShield: TelefunctionShield): string {
  return StringBetter(telefunctionShield)
}
// Like `String()` but with support for objects and arrays
function StringBetter(thing: unknown): string {
  if (isSchemaLike(thing)) {
    return getSchemaName(thing)
  }
  if (isPlainObject(thing)) {
    let str = ''
    const entries = Object.entries(thing)
    entries.forEach(([key, val], i) => {
      str += `${String(key)}:${StringBetter(val)}`
      const isLast = i === entries.length - 1
      if (!isLast) {
        str += ','
      }
    })
    str = `{${str}}`
    return str
  }
  if (Array.isArray(thing)) {
    return `[${thing.map((el) => StringBetter(el)).join(',')}]`
  }
  return String(thing)
}

function verifyOuter(verifier: unknown, args: unknown): true | string {
  assert(Array.isArray(args))
  if (Array.isArray(verifier)) {
    verifier = shield.type.tuple(...verifier)
    assert(isVerifierTuple(verifier))
  }
  if (isVerifierTuple(verifier)) {
    return verifyRecursive(verifier, args, '[root]')
  }
  assert(false)
}
function verifyRecursive(verifier: unknown, arg: unknown, breadcrumbs: string): true | string {
  assert(breadcrumbs.startsWith('[root]'))

  if (isVerifier(verifier)) {
    return verifier(arg, breadcrumbs)
  }

  if (isSchemaLike(verifier)) {
    return verifySchema(verifier, arg, breadcrumbs)
  }

  if (isPlainObject(verifier)) {
    const obj = verifier
    return verifyObject(obj, arg, breadcrumbs)
  }

  if (verifier === undefined) {
    return (shield.type.const(undefined) as any as Verifier)(arg, breadcrumbs)
  }

  const errorPrefix = `[shield()] Bad shield definition: ${breadcrumbs}`
  const errorSuffix = `See https://telefunc.com/shield`
  assertUsage(
    !Array.isArray(verifier),
    errorPrefix +
      ' is a plain JavaScript array which is forbidden: use `shield.type.tuple()` instead of `[]`. ' +
      errorSuffix,
  )
  assertUsage(
    false,
    `${errorPrefix} is \`${getTypeName(
      verifier,
    )}\` which is forbidden. Always use \`shield.type[x]\` or a plain JavaScript Object. ${errorSuffix}`,
  )
}

function verifyObject(obj: Record<string, unknown>, arg: unknown, breadcrumbs: string): true | string {
  if (!isPlainObject(arg)) {
    return errorMessage(breadcrumbs, getTypeName(arg), 'object')
  }
  for (const key of unique([...Object.keys(obj), ...Object.keys(arg)])) {
    const res = verifyRecursive(obj[key], arg[key], `${breadcrumbs} > [object: value of key \`${key}\`]`)
    if (res !== true) {
      return res
    }
  }
  return true
}

const type = (() => {
  const or = <T extends unknown[]>(...elements: T): T[number] => {
    const verifier = (input: unknown, breadcrumbs: string) => {
      const typeTargets = elements.map((el) => verifyRecursive(el, input, `${breadcrumbs}`))
      if (typeTargets.includes(true)) {
        return true
      }
      return `${breadcrumbs} is of wrong type`
    }
    markVerifier(verifier)
    verifier.toString = () => elements.map((el) => StringBetter(el)).join('|')
    return verifier as any
  }
  const tuple = <T extends unknown[]>(...elements: T): T => {
    const verifier = (input: unknown, breadcrumbs: string) => {
      if (!Array.isArray(input)) {
        return errorMessage(breadcrumbs, getTypeName(input), 'tuple')
      }
      const errorMessages = [...Array(Math.max(input.length, elements.length)).keys()]
        .map((i) =>
          verifyRecursive(
            i > elements.length - 1 ? type.const(undefined) : elements[i],
            input[i],
            `${breadcrumbs} > [tuple: element ${i}]`,
          ),
        )
        .filter((res) => res !== true)
      if (errorMessages.length === 0) {
        return true
      }
      return errorMessages[0]!
    }
    markVerifier(verifier)
    markVerifierTuple(verifier)
    verifier.toString = () => StringBetter(elements)
    return verifier as any
  }
  const array = <T>(arrayType: T): T[] => {
    const verifier = (input: unknown, breadcrumbs: string) => {
      if (!Array.isArray(input)) {
        return errorMessage(breadcrumbs, getTypeName(input), 'array')
      }
      const errorMessages = input
        .map((_, i) => verifyRecursive(arrayType, input[i], `${breadcrumbs} > [array element ${i}]`))
        .filter((res) => res !== true)
      if (errorMessages.length === 0) {
        return true
      }
      return errorMessages[0]!
    }
    markVerifier(verifier)
    verifier.toString = () => {
      let s = StringBetter(arrayType)
      if (s.includes(',')) {
        s = `(${s})`
      }
      s = `${s}[]`
      return s
    }
    return verifier as any
  }
  const object = <T>(objectType: T): Record<string, T> => {
    const verifier = (input: unknown, breadcrumbs: string) => {
      if (typeof input !== 'object' || input === null || input.constructor !== Object) {
        return errorMessage(breadcrumbs, getTypeName(input), 'object')
      }
      const errorMessages = Object.entries(input)
        .map(([key, val]) => verifyRecursive(objectType, val, `${breadcrumbs} > [object: value of key \`${key}\`]`))
        .filter((res) => res !== true)
      if (errorMessages.length === 0) {
        return true
      }
      return errorMessages[0]!
    }
    markVerifier(verifier)
    verifier.toString = () => {
      let s = StringBetter(objectType)
      if (s.includes(',')) {
        s = `(${s})`
      }
      s = `Record<string, ${s}}`
      return s
    }
    return verifier as any
  }

  const const_ = <T extends Readonly<number> | Readonly<string> | Readonly<boolean> | undefined | null>(val: T): T => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      input === val ? true : errorMessage(breadcrumbs, String(input), String(val))
    markVerifier(verifier)
    verifier.toString = () => StringBetter(val)
    return verifier as any
  }

  const string = ((): string => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      typeof input === 'string' ? true : errorMessage(breadcrumbs, getTypeName(input), 'string')
    markVerifier(verifier)
    verifier.toString = () => 'string'
    return verifier as any
  })()
  const number = ((): number => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      typeof input === 'number' ? true : errorMessage(breadcrumbs, getTypeName(input), 'number')
    markVerifier(verifier)
    verifier.toString = () => 'number'
    return verifier as any
  })()
  const boolean = ((): boolean => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      input === true || input === false ? true : errorMessage(breadcrumbs, getTypeName(input), 'boolean')
    markVerifier(verifier)
    verifier.toString = () => 'boolean'
    return verifier as any
  })()
  const date = ((): Date => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      typeof input === 'object' && input !== null && input.constructor === Date
        ? true
        : errorMessage(breadcrumbs, getTypeName(input), 'date')
    markVerifier(verifier)
    verifier.toString = () => 'date'
    return verifier as any
  })()
  const file = ((): File => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      isLazyFile(input) ? true : errorMessage(breadcrumbs, getTypeName(input), 'file')
    markVerifier(verifier)
    verifier.toString = () => 'file'
    return verifier as any
  })()
  const blob = ((): Blob => {
    const verifier = (input: unknown, breadcrumbs: string) =>
      isLazyBlob(input) ? true : errorMessage(breadcrumbs, getTypeName(input), 'blob')
    markVerifier(verifier)
    verifier.toString = () => 'blob'
    return verifier as any
  })()
  const any = ((): any => {
    const verifier = () => true as const
    markVerifier(verifier)
    verifier.toString = () => 'any'
    return verifier as any
  })()

  return {
    string,
    number,
    boolean,
    date,
    file,
    blob,
    array,
    object,
    or,
    tuple,
    const: const_,
    optional: <T>(param: T): T | undefined => or(param, const_(undefined)),
    nullable: <T>(param: T): T | null => or(param, const_(null)),
    any,
  }
})()
shield.type = type

function errorMessage(breadcrumbs: string, is: string, should: string) {
  return `${breadcrumbs} is \`${is}\` but should be \`${should}\`.`
}

type Verifier = ((input: unknown, breadcrumbs: string) => true | string) & {
  [isVerifierKey]?: true
  [isVerifierTupleKey]?: true
}

function isVerifier(thing: unknown): thing is Verifier {
  return (thing as any) && (thing as any)[isVerifierKey] === true
}
function markVerifier(verifier: Verifier) {
  assert(isCallable(verifier))
  verifier[isVerifierKey] = true
}

function isVerifierTuple(thing: unknown): thing is Verifier {
  return isVerifier(thing) && thing[isVerifierTupleKey] === true
}
function markVerifierTuple(verifier: Verifier) {
  verifier[isVerifierTupleKey] = true
}

function getTypeName(thing: unknown): string {
  if (thing === null) {
    return 'null'
  }
  if (thing === undefined) {
    return 'undefined'
  }

  if (typeof thing === 'object') {
    assert(thing !== null)
    if (thing.constructor === Date) {
      return 'date'
    }
    if (isLazyFile(thing)) {
      return 'file'
    }
    if (isLazyBlob(thing)) {
      return 'blob'
    }
    if (Array.isArray(thing)) {
      return 'array'
    }
  }

  return typeof thing
}

function isSchemaLike(thing: unknown): thing is SchemaLike {
  return isStandardSchema(thing) || isZodLikeSchema(thing)
}
function isStandardSchema(thing: unknown): thing is StandardSchema {
  return (
    isPlainObject(thing) &&
    '~standard' in thing &&
    isPlainObject(thing['~standard']) &&
    typeof thing['~standard'].validate === 'function'
  )
}
function isZodLikeSchema(thing: unknown): thing is ZodLikeSchema {
  return isPlainObject(thing) && typeof thing.safeParse === 'function'
}

function verifySchema(schema: SchemaLike, input: unknown, breadcrumbs: string): true | string {
  if (isStandardSchema(schema)) {
    const result = schema['~standard'].validate(input)
    assertUsage(
      !isPromiseLike(result),
      `[shield()] Async standard schemas aren't supported yet. Use a synchronous schema with \`shield()\`.`,
    )
    return getSchemaValidationResult(result, schema['~standard'].vendor, breadcrumbs)
  }
  if (isZodLikeSchema(schema)) {
    const result = schema.safeParse(input)
    assertUsage(
      isZodLikeSchemaResult(result),
      '[shield()] A Zod-like schema `safeParse()` should return an object with a boolean `success` property.',
    )
    return result.success ? true : getSchemaValidationError(result.error?.issues, 'zod', breadcrumbs)
  }
  assert(false)
}

function getSchemaValidationResult(result: StandardSchemaResult, vendor: string, breadcrumbs: string): true | string {
  return result.issues && result.issues.length > 0 ? getSchemaValidationError(result.issues, vendor, breadcrumbs) : true
}

function getSchemaValidationError(
  issues: readonly SchemaIssue[] | undefined,
  vendor: string,
  breadcrumbs: string,
): string {
  const issue = issues?.[0]
  const path = issue?.path
  const pathBreadcrumbs =
    path && path.length > 0
      ? `${breadcrumbs} > [${vendor} schema path \`${path.map((segment) => String(segment)).join('.')}\`]`
      : breadcrumbs
  const message = typeof issue?.message === 'string' && issue.message ? issue.message : 'validation failed'
  return `${pathBreadcrumbs} ${message}`
}

function isPromiseLike(thing: unknown): thing is PromiseLike<unknown> {
  return !!thing && typeof (thing as PromiseLike<unknown>).then === 'function'
}

function isZodLikeSchemaResult(thing: unknown): thing is ZodLikeSchemaResult {
  return (
    isPlainObject(thing) &&
    'success' in thing &&
    typeof thing.success === 'boolean' &&
    (thing.success || ('error' in thing && isPlainObject(thing.error)))
  )
}

function getSchemaName(schema: SchemaLike): string {
  if (isStandardSchema(schema)) return `schema(${schema['~standard'].vendor})`
  if (isZodLikeSchema(schema)) return 'schema(zod)'
  assert(false)
}
