#:schema node_modules/wrangler/config-schema.json
name = "telefunc-cloudflare-vite-plugin-example"
main = "./dist/worker.js"
compatibility_date = "2025-01-10"

# Uncomment and configure these bindings as needed for your application

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# [[d1_databases]]
# binding = "MY_D1"
# database_name = "my-database"
# database_id = "your-database-id"

# [[r2_buckets]]
# binding = "MY_R2"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# Example environment variables for development
[env.development]
# MY_VARIABLE = "development_value"

# Example environment variables for staging
[env.staging]
# MY_VARIABLE = "staging_value"
